export const SCHEMA_CONTEXT_KEYS: ReadonlySet<string> = new Set([
  '$defs',
  'additionalProperties',
  'allOf',
  'anyOf',
  'contains',
  'definitions',
  'dependentSchemas',
  'else',
  'if',
  'items',
  'not',
  'oneOf',
  'patternProperties',
  'prefixItems',
  'properties',
  'propertyNames',
  'schema',
  'schemas',
  'then',
  'unevaluatedItems',
  'unevaluatedProperties',
]);

export const IGNORED_POINTER_NAME_TOKENS: ReadonlySet<string> = new Set([
  'allOf',
  'anyOf',
  'components',
  'content',
  'items',
  'oneOf',
  'paths',
  'post',
  'put',
  'patch',
  'get',
  'delete',
  'head',
  'trace',
  'options',
  'requestBody',
  'responses',
  'schema',
  'schemas',
]);

export const LIKELY_SCHEMA_KEYS = [
  '$ref',
  'additionalProperties',
  'allOf',
  'anyOf',
  'const',
  'discriminator',
  'enum',
  'format',
  'items',
  'not',
  'oneOf',
  'patternProperties',
  'properties',
  'required',
  'type',
] as const;

export const REF_REPLACEMENT_ALLOWED_KEYS: ReadonlySet<string> = new Set(['$ref', 'summary', 'description']);
